### ISSUE TITLE
404 on uatest when uploading a project after deleting a project

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#1006]
## Scenario on __uatest__:
- user uploads a project with some files
- user deletes the project
- user uploads the project with some files again
This last step fails with a 404 back from `https://swift.oit.duke.edu/v1/AUTH_frds_ua_test...` when uploading part of a file.
Error message in ddsclient: 
```
Failed to send file to external store. Error:404
   https://swift.oit.duke.edu/v1/AUTH_frds_ua_test/...
```

## Example script:
Script to reproduce this issue(assuming have OSX/python):
```
if [ ! -e env ]
then
  virtualenv env
fi
source env/bin/activate
pip install --upgrade DukeDSClient

mkdir data
for i in $(seq 20)
do
   mkfile -n 10M data/$i.dat
done

ddsclient upload -p test_project data
ddsclient delete -p test_project --force

# Fails for me here
# if I add a sleep here it succeeds
ddsclient upload -p test_project data

deactivate
```
FYI: @jonturneratduke 

Thanks,
John Bradley

**Comment by dmlond** [comment]
This is due to the background job to initialize the project not completing before you attempt to upload files to the project. We plan to address this with a more informative error response from the endpoint to create a file in a project before it is initialized allowing the client to discern a specific transient error, sleep, and retry.
