### ISSUE TITLE
Allow user to remove themselves from a project, if there is another user on the project.

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#577]
### Background

To accomplish a handover of a project we currently to do the following:
1. Give recipient user project permissions
2. Take away current user project permissions
Step 2 currently requires an auth token for the recipient user.
This would really help the bad end user experience we currently have where the recipient must find their private key and give it to the service before they can receive a project. With the current system they just click a link.
### Request

I was wondering if we could relax the restriction for removing project permissions to only check that there is another user on the project.

This would require modifying these changes:
DDS-214 #resolve User cannot remove their own system permission. #466

Thanks.

**Comment by dleehr** [comment]
:+1: Just to underscore - this would greatly simplify our workflow and improve the user experience.

Removing the sending user from a project is the only reason we wanted to get credentials for the recipient in the first place. It's why I was asking about registering with the auth service last week - so that the receiving user could remove the sender from the transferred project.
