### ISSUE TITLE
Collection Pagination Not Working

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#793]
I'm trying to use pagination and it's not working as described in the docs. It always returns all objects. This is happening in the `GET/children` and `GET/projects` endpoints. 

> For actions that return a collection of resources/objects, the number of objects returned will be paginated. The number of objects returned per page, and the desired page can be controlled using the query parameters page, and per_page. For example: /projects?per_page=25 will return the first 25 projects, and /projects?page=3&per_page=25 will return the third batch of 25 projects. Collection payloads will always be returned as an array of objects; the results property will reference the array as follows:

**Comment by dmann** [comment]
@caseychoiniere Looks like I didn't read your issue closely enough. I only added pagination to `GET /children` and missed `GET /projects`. I'll take care of the latter in a future pull request. But, in the meantime, can you let me know if pagination for `GET /children` is working as expected?

**Comment by caseychoiniere** [comment]
@dmann Thanks, it appears to work as expected. Nice work. I'll leave this open though until `GET/projects` has pagination. I'm pretty sure that all endpoints that return a collection of resources should have pagination available though. This would probably include `software agents`, `metadata templates`, `metadata properties` etc.

**Comment by dmann** [comment]
@caseychoiniere You're right, pagination should be implemented on all collection resources. But, since it wasn't, I was hesitant to put it in place without coordinating with you first. I guess I was trying to avoid a situation where the api wasn't returning the expected collection, by returning all the things.  :P 

So, for the moment, I'm planning on paginating `GET /projects` and then moving on to some of the bugs that are blocking the metadata feature. Then I come back around and paginate the rest of the collection endpoints at a later date. Does that work for you? 

Also, when I paginate an endpoint, do I need to warn you or will your code handle it gracefully? Just trying to avoid breaking your code.
