### ISSUE TITLE
Recurring 500 error when trying to delete projects (Production)

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#935]
This is from a Usersnap generated issue. The user logged two issues on 2/20/17. 

I'm closing the issues on the portal and migrating them here.

You can see the issues here:

https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/issues/600

https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/issues/601

**Comment by caseychoiniere** [comment]
FYI - I contacted the user to let them know we got their reported issue and they responded with a little more info. They said:

>Thanks Casey - I seem to be having much better success with uploads via the DukeDSClient by archiving content directories into tarballs first, then uploading (fewer, larger files instead of more, smaller files). The deletions I'm trying to do through the web interface are just for cleanup since I have a few partially-uploaded projects that I'd rather just start over with using the tar-then-upload strategy. The deletions also fail through the DukeDSClient. On my end this is just cosmetic, but the partial uploads are occupying space so it would be good to be able to actually make those go away.

Thanks for your quick reply!

Best,

-Dan

**Comment by dmann** [comment]
Unfortunately, our Papertrail logs filled up at about 1:25pm today. So, we have no record of the failure. If the project was particularly large, deleting it would probably take longer than our request-timeout window, which is currently returning 500 instead of 503 as the error code. Like many of our issues, this will be fixed when our background job system is released.
